(ns portkey.utils
  (:require [clojure.string :as s]
            [clojure.test :refer :all]
            [net.cgrand.xforms :as x]
            [portkey.awsgen :as gen :refer :all]))




;; Keep it here but no longer in used
;; Used it to validate ser-fns but it seems too complex on the long run
(defmacro deftest-aws-ser
  ([name {:keys [description-schema shape-to-test apply-on-protocols inputs expected-result] :as test-input}]
   `(deftest-aws-ser ~name nil ~test-input))
  ([name doc-string? {:keys [description-schema shape-to-test apply-on-protocols inputs expected-result]}]
   (assert (-> doc-string? (some-fn string? nil?)) "doc-string? must be a string or nil")
   `(deftest ~name
      ~doc-string?
      (doseq [protocol# ~apply-on-protocols
              input#    ~inputs
              :let      [description-schema# (assoc-in ~description-schema ["metadata" "protocol"] protocol#)
                         _#                  (doseq [shape# (keys (description-schema# "shapes"))]
                                               (eval (gen/generate-serialization-declare shape#)))
                         ser-fns#            (into {}
                                                   (map (fn [[sh#]]
                                                          [sh# (eval (gen/generate-serialization-function description-schema# sh#))]))
                                                   (get description-schema# "shapes"))
                         serialization-fun#  (ser-fns# ~shape-to-test)]]
        (is (= ~expected-result (serialization-fun# input#)))))))



(defmacro deftest-aws-request
  "Test whether the request payload that is generated by request-fn
  generates proper body as generated by aws cli.
  Don't send any request, expected-result is taken from aws cli results."    
  ([name {:keys [user-input lib-ns request-fn method body-fun expected-result] :as test-input}]
   `(deftest-aws-request ~name nil ~test-input))
  ([name doc-string? {:keys [user-input lib-ns request-fn method body-fun expected-result]}]
   (assert (-> doc-string? (some-fn string? nil?)) "doc-string? must be a string or nil")
   `(deftest ~name
      ~doc-string?
      (let [request-fn# (var-get (ns-resolve (find-ns (quote ~lib-ns))
                                             (quote ~request-fn)))]
        (is (= ~expected-result
               (-> ~user-input
                   request-fn#
                   (assoc :http.request.configuration/method ~method)
                   ~body-fun
                   :ring.request
                   :body)))))))
