(ns portkey.aws.elasticfilesystem.-2015-02-01 (:require [portkey.aws]))

(def
 endpoints
 '{"eu-west-1"
   {:credential-scope
    {:service "elasticfilesystem", :region "eu-west-1"},
    :ssl-common-name "elasticfilesystem.eu-west-1.amazonaws.com",
    :endpoint "https://elasticfilesystem.eu-west-1.amazonaws.com",
    :signature-version :v4},
   "us-east-2"
   {:credential-scope
    {:service "elasticfilesystem", :region "us-east-2"},
    :ssl-common-name "elasticfilesystem.us-east-2.amazonaws.com",
    :endpoint "https://elasticfilesystem.us-east-2.amazonaws.com",
    :signature-version :v4},
   "ap-southeast-2"
   {:credential-scope
    {:service "elasticfilesystem", :region "ap-southeast-2"},
    :ssl-common-name "elasticfilesystem.ap-southeast-2.amazonaws.com",
    :endpoint "https://elasticfilesystem.ap-southeast-2.amazonaws.com",
    :signature-version :v4},
   "eu-central-1"
   {:credential-scope
    {:service "elasticfilesystem", :region "eu-central-1"},
    :ssl-common-name "elasticfilesystem.eu-central-1.amazonaws.com",
    :endpoint "https://elasticfilesystem.eu-central-1.amazonaws.com",
    :signature-version :v4},
   "us-west-2"
   {:credential-scope
    {:service "elasticfilesystem", :region "us-west-2"},
    :ssl-common-name "elasticfilesystem.us-west-2.amazonaws.com",
    :endpoint "https://elasticfilesystem.us-west-2.amazonaws.com",
    :signature-version :v4},
   "us-east-1"
   {:credential-scope
    {:service "elasticfilesystem", :region "us-east-1"},
    :ssl-common-name "elasticfilesystem.us-east-1.amazonaws.com",
    :endpoint "https://elasticfilesystem.us-east-1.amazonaws.com",
    :signature-version :v4}})

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/tag-keys (clojure.spec.alpha/coll-of :portkey.aws.elasticfilesystem.-2015-02-01/tag-key :max-count nil))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/create-file-system-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/CreationToken] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/PerformanceMode :portkey.aws.elasticfilesystem.-2015-02-01/Encrypted :portkey.aws.elasticfilesystem.-2015-02-01/KmsKeyId]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.unsupported-availability-zone/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/unsupported-availability-zone (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.unsupported-availability-zone/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.describe-tags-response/next-marker (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/marker))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-response (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/Tags] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/Marker :portkey.aws.elasticfilesystem.-2015-02-01.describe-tags-response/NextMarker]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-request (portkey.awsgen/json-keys :req-un [] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/MaxItems :portkey.aws.elasticfilesystem.-2015-02-01/Marker :portkey.aws.elasticfilesystem.-2015-02-01/CreationToken :portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.bad-request/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/bad-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.bad-request/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-count (clojure.spec.alpha/and clojure.core/int? (fn* [p1__99566__99567__auto__] (clojure.core/<= 0 p1__99566__99567__auto__))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/security-group (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/subnet-id (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/delete-file-system-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/create-mount-target-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01/SubnetId] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/IpAddress :portkey.aws.elasticfilesystem.-2015-02-01/SecurityGroups]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.ip-address-in-use/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/ip-address-in-use (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.ip-address-in-use/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/security-groups (clojure.spec.alpha/coll-of :portkey.aws.elasticfilesystem.-2015-02-01/security-group :max-count 5))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/life-cycle-state (clojure.spec.alpha/conformer (clojure.core/let [m__99523__auto__ {"creating" "creating", :creating "creating", "available" "available", :available "available", "deleting" "deleting", :deleting "deleting", "deleted" "deleted", :deleted "deleted"}] (clojure.core/fn [s__99524__auto__] (m__99523__auto__ s__99524__auto__ :clojure.spec.alpha/invalid))) (clojure.core/comp clojure.core/keyword portkey.awsgen/dashed)))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/encrypted clojure.core/boolean?)

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/MountTargetId] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-limit-exceeded/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-limit-exceeded (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-limit-exceeded/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/owner-id (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/aws-account-id))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/size-in-bytes (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/file-system-size))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/number-of-mount-targets (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-count))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/creation-time (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/timestamp))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/name (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/tag-value))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-description (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/OwnerId :portkey.aws.elasticfilesystem.-2015-02-01/CreationToken :portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/CreationTime :portkey.aws.elasticfilesystem.-2015-02-01/LifeCycleState :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/NumberOfMountTargets :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/SizeInBytes :portkey.aws.elasticfilesystem.-2015-02-01/PerformanceMode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/Encrypted :portkey.aws.elasticfilesystem.-2015-02-01/KmsKeyId :portkey.aws.elasticfilesystem.-2015-02-01.file-system-description/Name]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/delete-tags-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01/TagKeys] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/marker (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/tag-key (clojure.spec.alpha/and clojure.core/string? (clojure.core/fn [s__99525__auto__] (clojure.core/<= 1 (clojure.core/count s__99525__auto__))) (clojure.core/fn [s__99526__auto__] (clojure.core/< (clojure.core/count s__99526__auto__) 128))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/tags (clojure.spec.alpha/coll-of :portkey.aws.elasticfilesystem.-2015-02-01/tag :max-count nil))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/network-interface-id (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.mount-target-conflict/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-conflict (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.mount-target-conflict/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.describe-file-systems-response/file-systems (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/file-system-descriptions))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.describe-file-systems-response/next-marker (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/marker))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-response (portkey.awsgen/json-keys :req-un [] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/Marker :portkey.aws.elasticfilesystem.-2015-02-01.describe-file-systems-response/FileSystems :portkey.aws.elasticfilesystem.-2015-02-01.describe-file-systems-response/NextMarker]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.security-group-limit-exceeded/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/security-group-limit-exceeded (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.security-group-limit-exceeded/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.mount-target-not-found/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-not-found (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.mount-target-not-found/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/error-message (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.incorrect-mount-target-state/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/incorrect-mount-target-state (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.incorrect-mount-target-state/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.subnet-not-found/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/subnet-not-found (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.subnet-not-found/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/error-code (clojure.spec.alpha/and clojure.core/string? (clojure.core/fn [s__99525__auto__] (clojure.core/<= 1 (clojure.core/count s__99525__auto__)))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.describe-mount-targets-response/mount-targets (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-descriptions))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.describe-mount-targets-response/next-marker (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/marker))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-response (portkey.awsgen/json-keys :req-un [] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/Marker :portkey.aws.elasticfilesystem.-2015-02-01.describe-mount-targets-response/MountTargets :portkey.aws.elasticfilesystem.-2015-02-01.describe-mount-targets-response/NextMarker]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-not-found/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-not-found/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.dependency-timeout/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/dependency-timeout (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.dependency-timeout/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/create-tags-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01/Tags] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-response (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/SecurityGroups] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-in-use/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-in-use (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-in-use/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/tag-value (clojure.spec.alpha/and clojure.core/string? (clojure.core/fn [s__99526__auto__] (clojure.core/< (clojure.core/count s__99526__auto__) 256))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-id (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/aws-account-id (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-size/value (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/file-system-size-value))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-size (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-size/Value] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/Timestamp]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/kms-key-id (clojure.spec.alpha/and clojure.core/string? (clojure.core/fn [s__99525__auto__] (clojure.core/<= 1 (clojure.core/count s__99525__auto__))) (clojure.core/fn [s__99526__auto__] (clojure.core/< (clojure.core/count s__99526__auto__) 2048))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/MaxItems :portkey.aws.elasticfilesystem.-2015-02-01/Marker]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.mount-target-description/owner-id (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/aws-account-id))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-description (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/MountTargetId :portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01/SubnetId :portkey.aws.elasticfilesystem.-2015-02-01/LifeCycleState] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.mount-target-description/OwnerId :portkey.aws.elasticfilesystem.-2015-02-01/IpAddress :portkey.aws.elasticfilesystem.-2015-02-01/NetworkInterfaceId]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.file-system-already-exists/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-already-exists (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode :portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.file-system-already-exists/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-descriptions (clojure.spec.alpha/coll-of :portkey.aws.elasticfilesystem.-2015-02-01/file-system-description :max-count nil))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.incorrect-file-system-life-cycle-state/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/incorrect-file-system-life-cycle-state (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.incorrect-file-system-life-cycle-state/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-descriptions (clojure.spec.alpha/coll-of :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-description :max-count nil))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/max-items (clojure.spec.alpha/and clojure.core/int? (fn* [p1__99566__99567__auto__] (clojure.core/<= 1 p1__99566__99567__auto__))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/delete-mount-target-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/MountTargetId] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.security-group-not-found/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/security-group-not-found (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.security-group-not-found/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/ip-address (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-request (portkey.awsgen/json-keys :req-un [] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/MaxItems :portkey.aws.elasticfilesystem.-2015-02-01/Marker :portkey.aws.elasticfilesystem.-2015-02-01/FileSystemId :portkey.aws.elasticfilesystem.-2015-02-01/MountTargetId]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/timestamp clojure.core/inst?)

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.tag/key (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/tag-key))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.tag/value (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/tag-value))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/tag (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01.tag/Key :portkey.aws.elasticfilesystem.-2015-02-01.tag/Value] :opt-un []))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.network-interface-limit-exceeded/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/network-interface-limit-exceeded (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.network-interface-limit-exceeded/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.internal-server-error/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.internal-server-error/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-id (clojure.spec.alpha/and clojure.core/string?))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/creation-token (clojure.spec.alpha/and clojure.core/string? (clojure.core/fn [s__99525__auto__] (clojure.core/<= 1 (clojure.core/count s__99525__auto__))) (clojure.core/fn [s__99526__auto__] (clojure.core/< (clojure.core/count s__99526__auto__) 64))))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/performance-mode (clojure.spec.alpha/conformer (clojure.core/let [m__99523__auto__ {"generalPurpose" "generalPurpose", :general-purpose "generalPurpose", "maxIO" "maxIO", :maxio "maxIO"}] (clojure.core/fn [s__99524__auto__] (m__99523__auto__ s__99524__auto__ :clojure.spec.alpha/invalid))) (clojure.core/comp clojure.core/keyword portkey.awsgen/dashed)))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01.no-free-addresses-in-subnet/message (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/error-message))
(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/no-free-addresses-in-subnet (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/ErrorCode] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01.no-free-addresses-in-subnet/Message]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/modify-mount-target-security-groups-request (portkey.awsgen/json-keys :req-un [:portkey.aws.elasticfilesystem.-2015-02-01/MountTargetId] :opt-un [:portkey.aws.elasticfilesystem.-2015-02-01/SecurityGroups]))

(clojure.spec.alpha/def :portkey.aws.elasticfilesystem.-2015-02-01/file-system-size-value clojure.core/int?)

(clojure.core/defn describe-mount-target-security-groups [input113609] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "GET", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/mount-targets/{MountTargetId}/security-groups"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-request input113609)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"MountTargetId" "MountTargetId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113608] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "MountTargetNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-not-found, "IncorrectMountTargetState" :portkey.aws.elasticfilesystem.-2015-02-01/incorrect-mount-target-state}] (if (clojure.core/= 200 (:status response113608)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-response (:body response113608))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113608 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113608)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113608}))])))))))
(clojure.spec.alpha/fdef describe-mount-target-security-groups :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-target-security-groups-response))

(clojure.core/defn describe-file-systems [input113611] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "GET", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/file-systems"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-request input113611)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {}) (portkey.awsgen/params-to-querystring {"MaxItems" "MaxItems", "Marker" "Marker", "CreationToken" "CreationToken", "FileSystemId" "FileSystemId"}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113610] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found}] (if (clojure.core/= 200 (:status response113610)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-response (:body response113610))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113610 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113610)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113610}))])))))))
(clojure.spec.alpha/fdef describe-file-systems :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/describe-file-systems-response))

(clojure.core/defn modify-mount-target-security-groups [input113613] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "PUT", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/mount-targets/{MountTargetId}/security-groups"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/modify-mount-target-security-groups-request input113613)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"MountTargetId" "MountTargetId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113612] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "MountTargetNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-not-found, "IncorrectMountTargetState" :portkey.aws.elasticfilesystem.-2015-02-01/incorrect-mount-target-state, "SecurityGroupLimitExceeded" :portkey.aws.elasticfilesystem.-2015-02-01/security-group-limit-exceeded, "SecurityGroupNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/security-group-not-found}] (if (clojure.core/= 204 (:status response113612)) [:result true] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113612 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113612)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113612}))])))))))
(clojure.spec.alpha/fdef modify-mount-target-security-groups :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/modify-mount-target-security-groups-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/modify-mount-target-security-groups-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))))

(clojure.core/defn delete-tags [input113615] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "POST", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/delete-tags/{FileSystemId}"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/delete-tags-request input113615)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"FileSystemId" "FileSystemId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113614] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found}] (if (clojure.core/= 204 (:status response113614)) [:result true] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113614 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113614)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113614}))])))))))
(clojure.spec.alpha/fdef delete-tags :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-tags-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-tags-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))))

(clojure.core/defn create-tags [input113617] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "POST", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/create-tags/{FileSystemId}"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/create-tags-request input113617)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"FileSystemId" "FileSystemId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113616] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found}] (if (clojure.core/= 204 (:status response113616)) [:result true] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113616 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113616)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113616}))])))))))
(clojure.spec.alpha/fdef create-tags :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-tags-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-tags-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))))

(clojure.core/defn create-mount-target [input113619] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "POST", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/mount-targets"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/create-mount-target-request input113619)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113618] (clojure.core/let [errors__109313__auto__ {"UnsupportedAvailabilityZone" :portkey.aws.elasticfilesystem.-2015-02-01/unsupported-availability-zone, "BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "IpAddressInUse" :portkey.aws.elasticfilesystem.-2015-02-01/ip-address-in-use, "MountTargetConflict" :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-conflict, "SecurityGroupLimitExceeded" :portkey.aws.elasticfilesystem.-2015-02-01/security-group-limit-exceeded, "SubnetNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/subnet-not-found, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found, "IncorrectFileSystemLifeCycleState" :portkey.aws.elasticfilesystem.-2015-02-01/incorrect-file-system-life-cycle-state, "SecurityGroupNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/security-group-not-found, "NetworkInterfaceLimitExceeded" :portkey.aws.elasticfilesystem.-2015-02-01/network-interface-limit-exceeded, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "NoFreeAddressesInSubnet" :portkey.aws.elasticfilesystem.-2015-02-01/no-free-addresses-in-subnet}] (if (clojure.core/= 200 (:status response113618)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-description (:body response113618))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113618 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113618)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113618}))])))))))
(clojure.spec.alpha/fdef create-mount-target :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-mount-target-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-mount-target-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-description))

(clojure.core/defn create-file-system [input113621] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "POST", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/file-systems"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/create-file-system-request input113621)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113620] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemAlreadyExists" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-already-exists, "FileSystemLimitExceeded" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-limit-exceeded}] (if (clojure.core/= 201 (:status response113620)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/file-system-description (:body response113620))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113620 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113620)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113620}))])))))))
(clojure.spec.alpha/fdef create-file-system :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-file-system-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/create-file-system-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/file-system-description))

(clojure.core/defn describe-tags [input113623] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "GET", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/tags/{FileSystemId}/"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-request input113623)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"FileSystemId" "FileSystemId"}) (portkey.awsgen/params-to-querystring {"MaxItems" "MaxItems", "Marker" "Marker"}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113622] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found}] (if (clojure.core/= 200 (:status response113622)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-response (:body response113622))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113622 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113622)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113622}))])))))))
(clojure.spec.alpha/fdef describe-tags :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/describe-tags-response))

(clojure.core/defn describe-mount-targets [input113625] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "GET", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/mount-targets"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-request input113625)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {}) (portkey.awsgen/params-to-querystring {"MaxItems" "MaxItems", "Marker" "Marker", "FileSystemId" "FileSystemId", "MountTargetId" "MountTargetId"}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113624] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found, "MountTargetNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-not-found}] (if (clojure.core/= 200 (:status response113624)) [:result (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-response (:body response113624))] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113624 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113624)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113624}))])))))))
(clojure.spec.alpha/fdef describe-mount-targets :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))) :ret (clojure.spec.alpha/and :portkey.aws.elasticfilesystem.-2015-02-01/describe-mount-targets-response))

(clojure.core/defn delete-mount-target [input113627] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "DELETE", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/mount-targets/{MountTargetId}"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/delete-mount-target-request input113627)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"MountTargetId" "MountTargetId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113626] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "DependencyTimeout" :portkey.aws.elasticfilesystem.-2015-02-01/dependency-timeout, "MountTargetNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/mount-target-not-found}] (if (clojure.core/= 204 (:status response113626)) [:result true] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113626 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113626)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113626}))])))))))
(clojure.spec.alpha/fdef delete-mount-target :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-mount-target-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-mount-target-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))))

(clojure.core/defn delete-file-system [input113629] (clojure.core/let [endpoint__109311__auto__ (portkey.aws.elasticfilesystem.-2015-02-01/endpoints portkey.aws/*region*)] (clojure.core/-> {:portkey.aws/signature-version (:signature-version endpoint__109311__auto__), :method "DELETE", :as :json-string-keys, :headers {"content-type" "application/json"}, :portkey.aws/credential-scope (:credential-scope endpoint__109311__auto__), :url (clojure.core/str (:endpoint (endpoints portkey.aws/*region*)) "/2015-02-01/file-systems/{FileSystemId}"), :body (clojure.spec.alpha/unform :portkey.aws.elasticfilesystem.-2015-02-01/delete-file-system-request input113629)} (portkey.awsgen/params-to-header {}) (portkey.awsgen/params-to-uri {"FileSystemId" "FileSystemId"}) (portkey.awsgen/params-to-querystring {}) (portkey.awsgen/params-to-payload nil) (clojure.core/update :body (fn* [p1__109310__109312__auto__] (clojure.core/some-> p1__109310__109312__auto__ cheshire.core/generate-string))) (portkey.aws/*http-client* (clojure.core/fn [response113628] (clojure.core/let [errors__109313__auto__ {"BadRequest" :portkey.aws.elasticfilesystem.-2015-02-01/bad-request, "InternalServerError" :portkey.aws.elasticfilesystem.-2015-02-01/internal-server-error, "FileSystemNotFound" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-not-found, "FileSystemInUse" :portkey.aws.elasticfilesystem.-2015-02-01/file-system-in-use}] (if (clojure.core/= 204 (:status response113628)) [:result true] [:exception (clojure.core/if-some [[type__109314__auto__ spec__109315__auto__] (clojure.core/find errors__109313__auto__ (clojure.core/get-in response113628 [:headers "x-amzn-ErrorType"]))] (clojure.core/let [m__109316__auto__ (clojure.spec.alpha/unform spec__109315__auto__ (cheshire.core/parse-string (:body response113628)))] (clojure.core/ex-info (clojure.core/str type__109314__auto__ ": " (:message m__109316__auto__)) m__109316__auto__)) (clojure.core/ex-info "Unexpected response" {:response response113628}))])))))))
(clojure.spec.alpha/fdef delete-file-system :args (clojure.spec.alpha/cat :sync (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-file-system-request) :async (clojure.spec.alpha/tuple :portkey.aws.elasticfilesystem.-2015-02-01/delete-file-system-request (clojure.spec.alpha/fspec :args (clojure.spec.alpha/cat :result clojure.core/any? :exception clojure.core/ex-data)))))
